### ISSUE TITLE
Too many scans in receiver queue: Dropping scans!

### ISSUE THREAD

**Issue by Heavydpan** [PepperlFuchs/ROS_driver#16]
Hi!
My customer start R2000 and start to get R2000 point data, but after 1 hour, the R2000 driver post err:Too many scans in receiver queue: Dropping scans!
They use TCP request to get R2000 data.

How to solve this issue?
Thannk you!

**Comment by ipa-hsd** [comment]
@Heavydpan you can ignore the message. It just says that there are too many scans (100 in this case) in queue and not all of them will be processed. Probably I will remove the log message if it is annoying.

**Comment by Heavydpan** [comment]
But after this message showed, they can't receive any data.

Is it other issue?

**Comment by ipa-hsd** [comment]
OK then it is an issue. I don't think not receiving data is directly related to the log message.

**Comment by Heavydpan** [comment]
Hi,
But after this message showed, they can't recieve any data.
Is it other issue?



---Original---

**Comment by NikolasE** [comment]
"not all of them will be processed" Does that mean that not all measured data will be available in subscribing nodes?

**Comment by ipa-hsd** [comment]
Yes the device sends data at a faster rate than the ROS driver can process it. So the driver maintains a queue internally. Once the queue becomes full, oldest scan data is dropped.

**Comment by NikolasE** [comment]
How many scans are getting dropped? And how big can the delay between capturing the data on the device and publishing it as laser-msg become? I think that removing the warning is not the right way to deal with that problem as it hides a potentially serious issue.

**Comment by ipa-hsd** [comment]
@Heavydpan there have been changes in the past couple of months. Could you please pull the `master` branch and try again?

**Comment by ipa-hsd** [comment]
Feel free to reopen the issue if this is not solved for you.
