### ISSUE TITLE
When call the httpGet(), the program is jam.

### ISSUE THREAD

**Issue by Heavydpan** [PepperlFuchs/ROS_driver#17]
Sometimes the network is breakdown, and the customer track the driver, when run in HttpCommandInterface::httpGet(), and boost::asio::read_until() and boost::asio::read() will jam, and can't exit with CRTL+C.
We also can do like this: connect() to R2000, and sleep 5s, in this 5s run "ifdown" in terminal, have the same issue.
My suggestion is when the network have this problem , the R2000 driver throw the exception and return, maybe you can modify the driver?

Thank you!

**Comment by ipa-hsd** [comment]
There have quite a few changes in the past couple of months. Could you please pull in the `master` branch and try again?

**Comment by ipa-hsd** [comment]
I will close this for now. Feel free to open if you still face the issue.
