### ISSUE TITLE
Is UDP supposed to work?

### ISSUE THREAD

**Issue by maxlein** [PepperlFuchs/ROS_driver#2]
Hi,

I am trying out the driver and I can't get it to work over UDP.  

First, there is a hardcoded udp address in `pfsdp_protocol.hpp`.  
Then at least parse_data() gets called but no scans are published...  

TCP is working.

**Comment by ipa-hsd** [comment]
Hi, are you using R2000? UDP for R2000 is not tested yet. Is this a blocking issue for you?

**Comment by maxlein** [comment]
Well, we are comparing the sick microscan against the r2000.  
And I see some time delay as you can see on the gif:  (the slow downs are from this gif recorder...)

![microscan vs r2000](https://user-images.githubusercontent.com/11796203/66830868-c605b700-ef56-11e9-8e50-8c0279d14633.gif)  

btw: it may occurred to you that r2000 has a quite high noise in comparison to the microscan.  
Do you have any suggestions for configuring the r2000 for localization tasks?

**Comment by ipa-hsd** [comment]
> And I see some time delay as you can see on the gif: (the slow downs are from this gif recorder...)  

To clarify, the delay is not observed because of the driver, right?

> it may occurred to you that r2000 has a quite high noise in comparison to the microscan.

I have not tested SICK scanner you mentioned, so I cannot compare. Can you check if you get the same noise if you use the Windows software for Pepperl+Fuchs?

**Comment by maxlein** [comment]
No, the delay is somewhere in the line from scanner to rviz.  
I was just referring to the gif not displaying smoothly.  

Something is buffering up, because after a restart of the driver the delay is gone but increases again as time is passing.

Yes, I have the same noise on Windows.

**Comment by ipa-hsd** [comment]
> No, the delay is somewhere in the line from scanner to rviz.

This is most probably an issue with incorrect calculation of `time_increment`. Can you test https://github.com/PepperlFuchs/ROS_driver/commit/2f94e06e9a47030f625e6ea7f43e3b2e9a957d3b and let me know if this solves your issue?

**Comment by ipa-hsd** [comment]
It is most probably an issue with incorrect calculation of `time_increment`. Can you test it with https://github.com/PepperlFuchs/ROS_driver/commit/0ee0024829ff4d0f6d27864ec84e2badb4b6aeec?

**Comment by maxlein** [comment]
Yes, that fixed it! Thanks for fast support.
