### ISSUE TITLE
.clang-format file is not clang-format ?

### ISSUE THREAD

**Issue by finger42** [PepperlFuchs/ROS_driver#30]
Generating an .clang-format file:

https://clang.llvm.org/docs/ClangFormat.html

Hot should it look like?

```
cat .clang-format 
---
Language:        Cpp
# BasedOnStyle:  Google
AccessModifierOffset: -2
AlignAfterOpenBracket: Align
AlignConsecutiveAssignments: false
AlignConsecutiveDeclarations: false
AlignEscapedNewlines: Left
AlignOperands:   true
...
```

This is just an example...

**Comment by ipa-hsd** [comment]
Formatting should be fixed with https://github.com/PepperlFuchs/ROS_driver/pull/40. Closing this for now.
