### ISSUE TITLE
Seg fault on ROS Noetic

### ISSUE THREAD

**Issue by Patrick-Lascombe** [PepperlFuchs/ROS_driver#32]
Hello,
I know that this driver is not yet released on Noetic, but when I tried to use it I got a Seg fault (error code -11).
The driver is properly launched and I receive the LaserScab but after a few seconds the error (seen below) pop.
The error `conversion of data from string failed` comes from the parameter "skip_scans" missing since the LiDAR I use is not a version 1.03 or newer. But I don't think it is the cause of the problem since it has a default value of 0.
My setup is Ubuntu 20.04 with ROS Noetic.

![Screenshot from 2020-10-13 09-37-16](https://user-images.githubusercontent.com/44769524/95830506-0ea5ab00-0d38-11eb-90f5-5d8ca6424af3.png)

**Comment by ipa-hsd** [comment]
Thanks for reporting. Yes this seems to be because of the version mismatch of the device and not because of Noetic. Would it be possible for you to test the driver against a newer device version? I will try to print out a cleaner error message in the mean-time.

**Comment by Patrick-Lascombe** [comment]
I'll see if we have a newer version in our offices and check it

**Comment by Patrick-Lascombe** [comment]
Tested on a newer device, and the same problem occurred. I'll try to check on another computer during the day to exclude my hardware configuration
![Screenshot from 2020-10-13 10-07-15](https://user-images.githubusercontent.com/44769524/95833434-e7e97380-0d3b-11eb-9c36-b0805705cc40.png)

**Comment by ipa-hsd** [comment]
Could you remove `skip_scans` from [this](https://github.com/PepperlFuchs/ROS_driver/blob/330a0425983c6b82f1b5c91e1f4d32b85b1d3075/pf_driver/include/pf_driver/pf/pfsdp_protocol.hpp#L385) line and comment out [this](https://github.com/PepperlFuchs/ROS_driver/blob/330a0425983c6b82f1b5c91e1f4d32b85b1d3075/pf_driver/include/pf_driver/pf/pfsdp_protocol.hpp#L390) line and try again?

**Comment by Patrick-Lascombe** [comment]
Same result, I do not think it comes from the different version. I now conduct my test on a R2000 which has the skip_scans function and the same problem occurs

**Comment by ipa-hsd** [comment]
I was able to build and run the code successfully in `Noetic`. Are you still having the issue? Could you please compile the code in `debug` mode 
```
catkin_make -DCMAKE_BUILD_TYPE=Debug
```
and run it with [gdb](http://wiki.ros.org/roslaunch/Tutorials/Roslaunch%20Nodes%20in%20Valgrind%20or%20GDB) (add the following to the `<node>` tag in your `launch` file)
```
launch-prefix="gdb -ex run --args" 
```

**Comment by ipa-hsd** [comment]
Feel free to reopen the issue if this is not solved for you.
