### ISSUE TITLE
ROS release

### ISSUE THREAD

**Issue by reinzor** [PepperlFuchs/ROS_driver#34]
I've seen you created a release zip in Github. What about releasing the package using bloom so that it can be added to the `rosdistro`?

**Comment by reinzor** [comment]
https://github.com/PepperlFuchs/ROS_driver/releases/tag/v1.0

**Comment by ipa-hsd** [comment]
Yes they are in the process of doing it. It should be done in the coming weeks.

**Comment by reinzor** [comment]
Another ping, we are waiting for an official ROS release :)

**Comment by reinzor** [comment]
@PepperlFuchs could you please elaborate on this?

**Comment by reinzor** [comment]
@ipa-hsd , @PepperlFuchs could you please elaborate on the plan with this driver? If not, we have no other choice than forking this driver and maintain a fork (which is obviously not desired for an open-source project).

**Comment by ipa-hsd** [comment]
@reinzor sorry for the delay, but there are some pending PRs which we are trying to merge ASAP. Since they are fixes to existing (minor) bugs, it would not make much sense to release the packages without these fixes (the driver "works" without these fixes though).

**Comment by ipa-hsd** [comment]
Finally it is done:  
https://github.com/ros/rosdistro/pull/28271  
https://github.com/PepperlFuchs/ROS_driver/releases/tag/1.1.0   

It takes few days till it is indexed and then you should be able to install the package. Thanks for your patience!
