### ISSUE TITLE
Where is r2300_allscans.launch

### ISSUE THREAD

**Issue by wsaihopfsg** [PepperlFuchs/ROS_driver#44]
The readme says 
"To visualize the 4 rings in RViz, run the following launch file:
```
roslaunch pf_driver r2300_allscans.launch
```
"
I can only find `r2300.launch` but not  `r2300_allscans.launch`.

Thank you

**Comment by ipa-hsd** [comment]
Sorry the `README` needs to be updated. You should be able to visualize all rings with `r2300.launch`. If you are using `Noetic`, please refer https://github.com/PepperlFuchs/ROS_driver/issues/42

**Comment by wsaihopfsg** [comment]
merged with #42
